class Huissier {
  final String name;
  final String? frenchName;
  final String court;
  final String phone;
  final String? email;
  final String? city;
  final String? address;
  final String? decision;
  final String? photoUrl;

  const Huissier({
    required this.name,
    this.frenchName,
    required this.court,
    required this.phone,
    this.email,
    this.city,
    this.address,
    this.decision,
    this.photoUrl,
  });
}

const List<Huissier> huissiersData = [
  // Page 7
  Huissier(
    name: 'يوسف بولعيش',
    frenchName: 'Youssef Boulaich',
    court: 'ابتدائية تطوان',
    phone: '0661350616 / 0662060042',
    email: 'Youssefboulaichjustice@gmail.com',
    address: '21 شارع المقاومة الطابق 4 المكتب رقم 15 تطوان',
    decision: '2025/1812',
    photoUrl: 'assets/images/huissiers/1.jpeg',
  ),
  Huissier(
    name: 'أحمد الوهابي',
    frenchName: 'Ahmed El Ouahabi',
    court: 'ابتدائية تطوان',
    phone: '0661630120',
    email: 'Youssefboulaichjustice@gmail.com',
    address: 'شارع 9 ابريل إقامة بلال الطابق 3 المكتب رقم 5 حي الولاية تطوان',
    decision: '2025/1813',
    photoUrl: 'assets/images/huissiers/2.jpeg',
  ),
  Huissier(
    name: 'عبد القادر ديدوح',
    frenchName: 'Abdelkader Didouh',
    court: 'ابتدائية تطوان',
    phone: '0661571339',
    email: 'Youssefboulaichjustice@gmail.com',
    address: '21 شارع المقاومة الطابق 4 المكتب رقم 16 تطوان',
    decision: '2025/1814',
    photoUrl: 'assets/images/huissiers/3.jpeg',
  ),
  Huissier(
    name: 'عبد الحي الكراسي',
    frenchName: 'Abdelhay El Crasi',
    court: 'ابتدائية تطوان',
    phone: '0661287937',
    email: 'elcrasiabdelhay@gmail.com',
    address: '13 شارع يعقوب المنصور الطابق 2 المكتب رقم 10 تطوان',
    decision: '2025/1815',
    photoUrl: 'assets/images/huissiers/4.jpeg',
  ),
  Huissier(
    name: 'المهدي أحبار',
    frenchName: 'Mehdi Ahbar',
    court: 'ابتدائية تطوان',
    phone: '0661322474',
    email: 'ahbar.elmehdi@gmail.com',
    address: '13 شارع يعقوب المنصور الطابق 2 المكتب رقم 10 تطوان',
    decision: '2025/1816',
    photoUrl: 'assets/images/huissiers/5.jpeg',
  ),
  Huissier(
    name: 'نور الدين الشطويطي',
    frenchName: 'Noureddine Chatwiti',
    court: 'ابتدائية تطوان',
    phone: '0661068434',
    email: 'nchatwiti@gmail.com',
    address: '13 شارع يعقوب المنصور الطابق 2 المكتب رقم 10 تطوان',
    decision: '2025/1817',
    photoUrl: 'assets/images/huissiers/6.jpeg',
  ),
  Huissier(
    name: 'محمد امورغي',
    frenchName: 'Mohammad Amourghi',
    court: 'ابتدائية تطوان',
    phone: '0661614510',
    email: 'amourgha.mehmet@gmail.com',
    address: 'شارع 9 أبريل إقامة بلال ط 3 رقم 5 حي الولاية تطوان',
    decision: '2025/1818',
    photoUrl: 'assets/images/huissiers/7.jpeg',
  ),
  Huissier(
    name: 'حميد بوشباطة',
    frenchName: 'Hamid Bouchibata',
    court: 'ابتدائية تطوان',
    phone: '0672776484',
    email: 'Youssefboulaichjustice@gmail.com',
    address: '13 شارع يعقوب المنصور ط 2 رقم 10 تطوان',
    decision: '2025/1828',
    photoUrl: 'assets/images/huissiers/8.jpeg',
  ),
  Huissier(
    name: 'محمد الأزرق',
    frenchName: 'Mohammad Lazrak',
    court: 'ابتدائية تطوان',
    phone: '0672817247',
    email: 'lazrakm554@gmail.com',
    address: 'شارع غرغيز إقامة مبروكة رقم 7 تطوان',
    decision: '2025/1830',
    photoUrl: 'assets/images/huissiers/9.jpeg',
  ),
  Huissier(
    name: 'بدر الدين بوعزة',
    frenchName: 'Badreddine Bouazza',
    court: 'ابتدائية تطوان',
    phone: '0661287937',
    email: 'badreddinebouazza7.bb@gmail.com',
    address: 'شارع غرغيز إقامة مبروكة رقم 7 تطوان',
    decision: '2025/1831',
    photoUrl: 'assets/images/huissiers/10.jpeg',
  ),
  // Page 8
  Huissier(
    name: 'محمد علي بن صالح',
    frenchName: 'Mohamed Ali Ben Salah',
    court: 'ابتدائية تطوان',
    phone: '0667036465 / 0660500888',
    email: 'bensalahhuissier@gmail.com',
    address: 'شارع محمد بن الحسن الوزاني زنقة 1 إقامة حياة ط 1 رقم 1 تطوان',
    decision: '2025/1833',
    photoUrl: 'assets/images/huissiers/11.jpeg',
  ),
  Huissier(
    name: 'علوش محمد',
    frenchName: 'Mohammad Al Luch',
    court: 'ابتدائية تطوان',
    phone: '0673102771',
    email: 'Youssefboulaichjustice@gmail.com',
    address: '13 شارع يعقوب المنصور الطابق 2 المكتب رقم 10 تطوان',
    decision: '2025/1832',
    photoUrl: 'assets/images/huissiers/12.jpeg',
  ),
  Huissier(
    name: 'محمد علي الحسني',
    frenchName: 'Mohamed Ali El Husni',
    court: 'ابتدائية تطوان',
    phone: '0661356670',
    email: 'mohamedalielhusni@gmail.com',
    address: 'شارع 9 ابريل إقامة بلال الطابق 3 المكتب رقم 5 حي الولاية تطوان',
    decision: '2011/41',
    photoUrl: 'assets/images/huissiers/13.jpeg',
  ),
  Huissier(
    name: 'عمر العياشي',
    frenchName: 'Omar Layachi',
    court: 'ابتدائية تطوان',
    phone: '0661571339',
    email: 'olayachi.huissier@gmail.com',
    address: 'شارع محمد الحصناوي إقامة أحلام الطابق 2 المكتب رقم 4 حي الولاية تطوان',
    decision: '2025/1842',
    photoUrl: 'assets/images/huissiers/14.jpeg',
  ),
  Huissier(
    name: 'رشيد بنيس',
    frenchName: 'Rachid Bennis',
    court: 'ابتدائية تطوان',
    phone: '0661383085',
    email: 'huissier.rachidbennis@gmail.com',
    address: '21 شارع المقاومة الطابق 4 المكتب رقم 20 تطوان',
    decision: '2025/1835',
    photoUrl: 'assets/images/huissiers/15.jpeg',
  ),
  Huissier(
    name: 'إدريس أمورغي',
    frenchName: 'Driss Amorgha',
    court: 'ابتدائية تطوان',
    phone: '0661353869',
    email: 'drissamorgha@gmail.com',
    address: 'شارع محمد الخامس قيسارية القاهرة الطابق 1 المكتب رقم 58 تطوان',
    decision: '2025/1836',
    photoUrl: 'assets/images/huissiers/16.jpeg',
  ),
  Huissier(
    name: 'جمال السباعي',
    frenchName: 'Jamal Sbai',
    court: 'ابتدائية تطوان',
    phone: '0661378668 / 0667130682',
    email: 'Hjsbaijamal@gmail.com',
    address: 'شارع محمد الحصناوي إقامة أحلام الطابق 3 المكتب رقم 05 حي الولاية تطوان',
    decision: '2025/1837',
    photoUrl: 'assets/images/huissiers/17.jpeg',
  ),
  // Page 9
  Huissier(
    name: 'حسناء بنقابو',
    frenchName: 'Hasnaa Ben Kabbou',
    court: 'ابتدائية تطوان',
    phone: '0539724965 / 0661480989',
    email: 'Huissiere@benkabou.ma',
    address: 'شارع علي يعتة ولاية سنتر الطابق 4 المكتب رقم 44 حي الولاية تطوان',
    decision: '2025/1838',
    photoUrl: 'assets/images/huissiers/18.jpeg',
  ),
  Huissier(
    name: 'مصطفى مرزيق',
    frenchName: 'Mostapha Mrizek',
    court: 'ابتدائية تطوان',
    phone: '0662128008',
    email: 'Mostaphamr@live.fr',
    address: 'شارع محمد بن ألحسن ألوَزّاني زنقة 1 أقامة حياة ط 1 رقم 1 تطوان',
    decision: '2025/1839',
    photoUrl: 'assets/images/huissiers/19.jpeg',
  ),
  Huissier(
    name: 'عادل أكبادي',
    frenchName: 'Adel Qbadi',
    court: 'ابتدائية تطوان',
    phone: '0668010921',
    email: 'olayachi.huissier@gmail.com',
    address: 'شارع 9 أبريل إقامة بلال الطابق 3 المكتب رقم 5 حي الولاية تطوان',
    decision: '2025/1840',
    photoUrl: 'assets/images/huissiers/20.jpeg',
  ),
  Huissier(
    name: 'حفيظ موسى',
    frenchName: 'Hafid Moussa',
    court: 'ابتدائية تطوان',
    phone: '0661287937',
    email: 'Hafidmoussa966@gmail.com',
    address: 'شارع علي يعتة المركز التجاري الولاية سنتر ط 2 رقم 16 تطوان',
    decision: '2025/1841',
    photoUrl: 'assets/images/huissiers/21.jpeg',
  ),
  Huissier(
    name: 'عثمان بوزيان',
    frenchName: 'Otman Bouzian',
    court: 'ابتدائية تطوان',
    phone: '0661506081',
    email: 'bouzian10@hotmail.com',
    address: 'شارع 9 أبريل إقامة بلال الطابق 3 المكتب رقم 5 حي الولاية تطوان',
    decision: '2025/1844',
    photoUrl: 'assets/images/huissiers/22.jpeg',
  ),
  Huissier(
    name: 'فاطمة الخنسي',
    frenchName: 'Fatima Yel khounssi',
    court: 'ابتدائية تطوان',
    phone: '0660021906',
    email: 'ELKHOUNSSIFATIMA@GMAIL.COM',
    address: '13 شارع يعقوب المنصور الطابق 2 المكتب رقم 10 تطوان',
    decision: '2025/1847',
    photoUrl: 'assets/images/huissiers/23.jpeg',
  ),
  // Page 10
  Huissier(
    name: 'هاجر الوهابي',
    frenchName: 'Hajar El Ouahabi',
    court: 'ابتدائية تطوان',
    phone: '0661459836',
    email: 'hajartetouania20@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم الطابق 3 المكتب رقم 12 تطوان',
    decision: '2025/1848',
    photoUrl: 'assets/images/huissiers/24.jpeg',
  ),
  Huissier(
    name: 'خالد لمسيح',
    frenchName: 'Khalid Lamsiah',
    court: 'ابتدائية تطوان',
    phone: '0661861368',
    email: 'khalid.lamsiah1986@gmail.com',
    address: 'شارع علي يعتة المركز التجاري الولاية سنتر ط 2 رقم 14 تطوان',
    decision: '2025/1849',
    photoUrl: 'assets/images/huissiers/25.jpeg',
  ),
  Huissier(
    name: 'هشام المزياتي',
    frenchName: 'hicham el mezyaty',
    court: 'ابتدائية تطوان',
    phone: '0661696225',
    email: 'Hichamelmezyaty1990@gmail.com',
    address: 'شارع 9 ابريل إقامة ادم ط 3 رقم 12 تطوان',
    decision: '2025/1850',
    photoUrl: 'assets/images/huissiers/26.jpeg',
  ),
  Huissier(
    name: 'ابتسام المدغري الفيلالي',
    frenchName: 'Ibtissam Lamdaghri Filali',
    court: 'ابتدائية تطوان',
    phone: '0661069578',
    email: 'ilamdaghrifilali@gmail.com',
    address: 'شارع محمد الحنصالي إقامة حالم ط 1 2الشقة رقم 4 حي الولاية تطوان',
    decision: '2025/1846',
    photoUrl: 'assets/images/huissiers/27.jpeg',
  ),
  Huissier(
    name: 'عبد المنعم الغريسي',
    frenchName: 'Abdelmounaim El Ghrissi',
    court: 'ابتدائية تطوان',
    phone: '0661696722',
    email: 'Elghrissy@gmail.com',
    address: 'شارع محمد الحنصالي إقامة احلام الطابق 3 رقم 5 تطوان',
    decision: '2025/1851',
    photoUrl: 'assets/images/huissiers/28.jpeg',
  ),
  Huissier(
    name: 'محمد البقالي القاسمي',
    frenchName: 'Mohammed El Bakkali El Kassimi',
    court: 'ابتدائية تطوان',
    phone: '0661627332',
    email: 'hj.elbakkalielkassimi2016@gmail.com',
    address: 'شارع محمد ألحنصالي أقامة أحلام ط 2 الشقة رقم 4 حي الولاية تطوان',
    decision: '2025/1852',
    photoUrl: 'assets/images/huissiers/29.jpeg',
  ),
  // Page 11
  Huissier(
    name: 'محمد رضى المسعودي',
    frenchName: 'Mohmmmed-reda El Mesaoudi',
    court: 'ابتدائية تطوان',
    phone: '0661350616 / 0662060042',
    email: 'redaelmesaoudi@gmail.com',
    address: '21 شارع المقاومة الطابق 4 المكتب رقم 15 تطوان',
    decision: '2025/1853',
    photoUrl: 'assets/images/huissiers/30.jpeg',
  ),
  Huissier(
    name: 'احمد اطويشار',
    frenchName: 'Ahmed Touichar',
    court: 'ابتدائية تطوان',
    phone: '0670953132',
    email: 'ahmedtouichar17@gmail.com',
    address: 'شارع محمد الحنصالي إقامة احلام ط 3الشقة رقم 6 حي الولاية تطوان',
    decision: '2025/1854',
    photoUrl: 'assets/images/huissiers/31.jpeg',
  ),
  Huissier(
    name: 'انس احنون',
    frenchName: 'Anas Ahnoun',
    court: 'ابتدائية تطوان',
    phone: '0630980183',
    email: 'anasahnoun@gmail.com',
    address: 'شارع 9ابريل إقامة ادم ط 3 رقم 12تطوان',
    decision: '2025/1857',
    photoUrl: 'assets/images/huissiers/32.jpeg',
  ),
  Huissier(
    name: 'عبد اللطيف احيتاف',
    frenchName: 'Abdellatif Aheitaf',
    court: 'ابتدائية تطوان',
    phone: '0662147873',
    email: 'ahaitaf.abdellatif@gmail.com',
    address: 'شارع محمد الحنصالي إقامة احلام ط 3الشقة رقم 6حي الولاية تطوان',
    decision: '2025/1856',
    photoUrl: 'assets/images/huissiers/33.jpeg',
  ),
  Huissier(
    name: 'محمد ايمن اولاد بن علي',
    frenchName: 'Mohamed Aiman Aoulad Ben Ali',
    court: 'ابتدائية تطوان',
    phone: '0673188971',
    email: 'justice.aiman@gmail.com',
    address: '47 شارع محمد الخامس ط 1رقم 1قبالة وكالة CIHبنك تطوان',
    decision: '2025/1862',
    photoUrl: 'assets/images/huissiers/34.jpeg',
  ),
  // Page 12
  Huissier(
    name: 'فاطمة اليحياوي',
    frenchName: 'Fatima Elyahyaoui',
    court: 'ابتدائية تطوان',
    phone: '0639417913',
    email: 'fatimaelyahyaoui90@gmail.com',
    address: 'شارع شكيب ارسلان رقم 67 الطابق الاول رقم 02تطوان',
    decision: '2025/1863',
    photoUrl: 'assets/images/huissiers/35.jpeg',
  ),
  // Tetouan Continuation
  Huissier(
    name: 'أحمد المودن',
    frenchName: 'Ahmed Elmouedden',
    court: 'ابتدائية تطوان',
    phone: '0653807092',
    email: 'elmoueddenhuissier@gmail.com',
    address: 'شارع محمد الخامس ط 1 رقم 1 قبالة وكالة CIH بنك تطوان',
    decision: '2025/1864',
    photoUrl: 'assets/images/huissiers/36.jpeg',
  ),
  Huissier(
    name: 'سفيان الداودي',
    frenchName: 'Soufiane Daoudi',
    court: 'ابتدائية تطوان',
    phone: '0667094539',
    email: 'soufianedaoudi.huissier@gmail.com',
    address: '49 شارع محمد الخامس ط 1 رقم 1 قبالة وكالة CIH بنك تطوان',
    decision: '2025/1866',
    photoUrl: 'assets/images/huissiers/37.jpeg',
  ),
  Huissier(
    name: 'بلال محراش',
    frenchName: 'Bilal Mahrach',
    court: 'ابتدائية تطوان',
    phone: '0620656084',
    email: 'bilalmahrach10@gmail.com',
    address: 'شارع محمد بن الحسن الوزاني زنقة 1 إقامة حياة ط 1 رقم 1 تطوان',
    decision: '2025/1867',
    photoUrl: 'assets/images/huissiers/38.jpeg',
  ),
  Huissier(
    name: 'خالد النجار',
    frenchName: 'Khaled Nejjar',
    court: 'ابتدائية تطوان',
    phone: '0677838292',
    email: 'khaled.nejjar@gmail.com',
    address: 'شارع شكيب أرسلان رقم 67 الطابق الأول رقم 02 تطوان',
    decision: '2025/1868',
    photoUrl: 'assets/images/huissiers/39.jpeg',
  ),
  Huissier(
    name: 'ياسين أقاش',
    frenchName: 'Yassin Akach',
    court: 'ابتدائية تطوان',
    phone: '0656608763',
    email: 'yassinakachhuissier@gmail.com',
    address: 'شارع شكيب أرسلان رقم 67 الطابق الأول رقم 02 تطوان',
    decision: '2025/1870',
    photoUrl: 'assets/images/huissiers/40.jpeg',
  ),
  Huissier(
    name: 'بلال الدردابي',
    frenchName: 'Bilal Derdabi',
    court: 'ابتدائية تطوان',
    phone: '0676327844',
    email: 'bilal.derdabi.hj@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم ط 1 رقم 02 تطوان',
    decision: '2025/1871',
    photoUrl: 'assets/images/huissiers/41.jpeg',
  ),
  Huissier(
    name: 'عائشة التجكاني',
    frenchName: 'Aicha Touggani',
    court: 'ابتدائية تطوان',
    phone: '0673378412',
    email: 'aicha.touggani@gmail.com',
    address: 'شارع محمد الخامس ط 1 رقم 1 قبالة وكالة CIH بنك تطوان',
    decision: '2025/1873',
    photoUrl: 'assets/images/huissiers/42.jpeg',
  ),
  Huissier(
    name: 'طه الرحموني',
    frenchName: 'Taha Rahmouni',
    court: 'ابتدائية تطوان',
    phone: '0600564086',
    email: 'TahaRahmouniAlami@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم الطابق 3 المكتب رقم 12 تطوان',
    decision: '2025/1874',
    photoUrl: 'assets/images/huissiers/43.jpeg',
  ),
  Huissier(
    name: 'أيوب بخات',
    frenchName: 'Ayoub Bakhat',
    court: 'ابتدائية تطوان',
    phone: '0671062134',
    email: 'ayoubbakhat8@gmail.com',
    address: 'شارع محمد بنونة زنقة الشرف رقم 13 تطوان',
    decision: '2025/1876',
    photoUrl: 'assets/images/huissiers/44.jpeg',
  ),
  Huissier(
    name: 'حسن خالص',
    frenchName: 'Hassan Khales',
    court: 'ابتدائية تطوان',
    phone: '0770112400',
    email: 'hassankhales1979@gmail.com',
    address: 'شارع شكيب أرسلان رقم 67 الطابق الأول رقم 02 تطوان',
    decision: '2025/1879',
    photoUrl: 'assets/images/huissiers/45.jpeg',
  ),
  Huissier(
    name: 'حميد الهواري',
    frenchName: 'Hamid Haouari',
    court: 'ابتدائية تطوان',
    phone: '0610302117',
    email: 'hamid.haouari1@gmail.com',
    address: 'شارع شكيب أرسلان رقم 67 الطابق الأول رقم 02 تطوان',
    decision: '2025/1882',
    photoUrl: 'assets/images/huissiers/46.jpeg',
  ),
  Huissier(
    name: 'أشرف أحكان',
    frenchName: 'Achraf Ahkan',
    court: 'ابتدائية تطوان',
    phone: '0667096574',
    email: 'achraf.ahagane@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم ط 1 رقم 02 تطوان',
    decision: '2025/1878',
    photoUrl: 'assets/images/huissiers/47.jpeg',
  ),
  Huissier(
    name: 'حاتم نقرو',
    frenchName: 'Hatim Nokro',
    court: 'ابتدائية تطوان',
    phone: '0690324352',
    email: 'mr.nokro.hatim@gmail.com',
    address: 'شارع محمد الحنصالي إقامة أحلام ط 3 الشقة رقم 6 حي الولاية تطوان',
    decision: '2025/1869',
    photoUrl: 'assets/images/huissiers/48.jpeg',
  ),
  Huissier(
    name: 'أيوب الزواي',
    frenchName: 'Ayoub Zouay',
    court: 'ابتدائية تطوان',
    phone: '0682422174',
    email: 'ayoubzouay90@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم ط 1 رقم 02 تطوان',
    decision: '2025/1881',
    photoUrl: 'assets/images/huissiers/49.jpeg',
  ),
  Huissier(
    name: 'منير بلوقي',
    frenchName: 'Mounir Belouki',
    court: 'ابتدائية تطوان',
    phone: '0661571339',
    email: 'mounirblk@hotmail.com',
    address: 'شارع الوحدة عمارة 14 الطابق 3 رقم 16 تطوان',
    decision: '2025/1872',
    photoUrl: 'assets/images/huissiers/50.jpeg',
  ),
  Huissier(
    name: 'أمال الصباحي',
    frenchName: 'Amal Misbahi',
    court: 'ابتدائية تطوان',
    phone: '0666383378',
    email: 'amalmisbahi363@gmail.com',
    address: 'شارع 9 أبريل إقامة بلال الطابق 3 المكتب رقم 5 حي الولاية تطوان',
    decision: '2025/1865',
    photoUrl: 'assets/images/huissiers/51.jpeg',
  ),
  Huissier(
    name: 'محمد شقلال',
    frenchName: 'Mohamed Cheklal',
    court: 'ابتدائية تطوان',
    phone: '0667092957',
    email: 'mohamedcheklal203@gmail.com',
    address: 'شارع 9 أبريل إقامة آدم الطابق 1 المكتب رقم 02 تطوان',
    decision: '2025/1880',
    photoUrl: 'assets/images/huissiers/52.jpeg',
  ),

  // TPI CHEFCHAOUEN
  Huissier(
    name: 'عبد الواحد البعبوع',
    frenchName: 'Abdelouahed Elbaaboua',
    court: 'ابتدائية شفشاون',
    phone: '0668107203',
    email: 'abdelouahid22112017@gmail.com',
    address: 'شارع سيدي السريقي حي الشرفاء، شفشاون',
    decision: '96/722',
    photoUrl: 'assets/images/huissiers/53.jpeg',
  ),
  Huissier(
    name: 'محمد علي المرابط',
    frenchName: 'Mohamed Ali El Mourabet',
    court: 'ابتدائية شفشاون',
    phone: '0661826519',
    email: 'TahaRahmouniAlami@gmail.com',
    address: 'شارع محمد عبده، شفشاون',
    decision: '2/243',
    photoUrl: 'assets/images/huissiers/54.jpeg',
  ),
  Huissier(
    name: 'عبد الخالق المرابط',
    frenchName: 'Abdelkhalek El Mourabet',
    court: 'ابتدائية شفشاون',
    phone: '0677860426',
    email: 'ayoubbakhat8@gmail.com',
    address: 'شارع عبد الكريم الخطابي شفشاون',
    decision: '96/724',
    photoUrl: 'assets/images/huissiers/55.jpeg',
  ),
  Huissier(
    name: 'خليد اجة',
    frenchName: 'Khalid Aja',
    court: 'ابتدائية شفشاون',
    phone: '0678205888',
    email: 'hassankhales1979@gmail.com',
    address: 'شارع مولاي عبد الرحمان الشريف قيسارية الجامع، شفشاون',
    decision: '27087',
    photoUrl: 'assets/images/huissiers/56.jpeg',
  ),
  Huissier(
    name: 'مراد بلخريف',
    frenchName: 'Morad Boulakhrif',
    court: 'ابتدائية شفشاون',
    phone: '0655854263',
    email: 'hamid.haouari1@gmail.com',
    address: 'شارع محمد الخامس زنقة موسى بن نصير 57، شفشاون',
    decision: '2011/418',
    photoUrl: 'assets/images/huissiers/57.jpeg',
  ),
  Huissier(
    name: 'محسن الشريف',
    frenchName: 'Mohsin Cherif',
    court: 'ابتدائية شفشاون',
    phone: '0694144167',
    email: 'achraf.ahagane@gmail.com',
    address: 'شارع سيدي السريقي حي الشرفاء، شفشاون',
    decision: '2018/117',
    photoUrl: 'assets/images/huissiers/58.jpeg',
  ),
  Huissier(
    name: 'محمد بنعمر',
    frenchName: 'Mohamed Benomar',
    court: 'ابتدائية شفشاون',
    phone: '0677924116',
    email: 'abdelouahid22112017@gmail.com',
    address: 'شارع محمد الخامس زنقة موسى بن نصير 57، شفشاون',
    decision: '2020/16',
    photoUrl: 'assets/images/huissiers/59.jpeg',
  ),
  Huissier(
    name: 'فاطمة الزهراء ميهاوي',
    frenchName: 'Fatima Zohra Mahyaoui',
    court: 'ابتدائية شفشاون',
    phone: '0668253888',
    email: 'huissier.mahyaoui@gmail.com',
    address: 'شارع محمد الخامس زنقة موسى بن نصير 57 شفشاون',
    decision: '2025/288',
    photoUrl: 'assets/images/huissiers/60.jpeg',
  ),
  Huissier(
    name: 'رجاء مساري',
    frenchName: 'Rajae Messari',
    court: 'ابتدائية شفشاون',
    phone: '0669393933',
    email: 'rajaemessari2021@gmail.com',
    address: 'شارع محمد الخامس زنقة موسى بن نصير 57 شفشاون',
    decision: '2025/445',
    photoUrl: 'assets/images/huissiers/61.jpeg',
  ),
  Huissier(
    name: 'سيف فضل',
    frenchName: 'Saif Fadl',
    court: 'ابتدائية شفشاون',
    phone: '0660573288',
    email: 'saifhuissier97@gmail.com',
    address: 'شارع مولاي عبد السلام وشارع المشيشي الحي الإداري ط 2 الشقة ر 5 شفشاون',
    decision: '27087',
    photoUrl: 'assets/images/huissiers/62.jpeg',
  ),
  Huissier(
    name: 'محمد المكودي',
    frenchName: 'Mohamed El Makoudi',
    court: 'ابتدائية شفشاون',
    phone: '0654581904',
    email: 'Mohammedmakoudi161@gmail.com',
    address: 'شارع مولاي عبد السلام وشارع المشيشي الحي الإداري ط 2 الشقة ر 5 شفشاون',
    decision: '2025/465',
    photoUrl: 'assets/images/huissiers/63.jpeg',
  ),
  Huissier(
    name: 'سمير بن حدايدة',
    frenchName: 'Samir Ben Hdaida',
    court: 'ابتدائية شفشاون',
    phone: '0666783630',
    email: 'samirbenhdaida.Huissier@gmail.com',
    address: 'شارع مولاي عبد السلام وشارع المشيشي الحي الإداري ط 2 الشقة ر 5 شفشاون',
    decision: '2025/467',
    photoUrl: 'assets/images/huissiers/64.jpeg',
  ),
  Huissier(
    name: 'مجيدة الشوتي',
    frenchName: 'Majida Ech-chouti',
    court: 'ابتدائية شفشاون',
    phone: '0610162033',
    email: 'majdachouti49@gmail.com',
    address: 'شارع سيدي السريقي حي الشرفاء شفشاون',
    decision: '2025/470',
    photoUrl: 'assets/images/huissiers/65.jpeg',
  ),
  Huissier(
    name: 'نور الدين شحموط',
    frenchName: 'Noureddin Chahmout',
    court: 'ابتدائية شفشاون',
    phone: '0660839316',
    email: 'huissierchahmout@gmail.com',
    address: 'شارع سيدي السريقي حي الشرفاء شفشاون',
    decision: '2025/577',
    photoUrl: 'assets/images/huissiers/66.jpeg',
  ),
  Huissier(
    name: 'حسام الحسني',
    frenchName: 'Houssam Housni',
    court: 'ابتدائية شفشاون',
    phone: '0721650292',
    email: 'houssamelhousni4@gmail.com',
    address: 'شارع مولاي عبد السلام وشارع المشيشي الحي الإداري ط 2 الشقة ر 5 شفشاون',
    decision: '2025/580',
    photoUrl: 'assets/images/huissiers/67.jpeg',
  ),

  // TPI OUEZZANE
  Huissier(
    name: 'إدريس عثماني',
    frenchName: 'Driss Outmani',
    court: 'ابتدائية وزان',
    phone: '0668107203',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2005',
    photoUrl: 'assets/images/huissiers/68.jpeg',
  ),
  Huissier(
    name: 'توفيق زنايدي',
    frenchName: 'Taoufik Zenaidi',
    court: 'ابتدائية وزان',
    phone: '0662115265',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2005',
    photoUrl: 'assets/images/huissiers/69.jpeg',
  ),
  Huissier(
    name: 'ياسر واهبي',
    frenchName: 'Yassir Ouahbi',
    court: 'ابتدائية وزان',
    phone: '0667905339',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2/26802',
    photoUrl: 'assets/images/huissiers/70.jpeg',
  ),
  Huissier(
    name: 'محمد الغزواني',
    frenchName: 'Mohamed El Ghazouani',
    court: 'ابتدائية وزان',
    phone: '0662532846',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2005',
    photoUrl: 'assets/images/huissiers/71.jpeg',
  ),
  Huissier(
    name: 'عبد السلام نصيف',
    frenchName: 'Abdesselam Nassif',
    court: 'ابتدائية وزان',
    phone: '0668313906',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2005',
    photoUrl: 'assets/images/huissiers/72.jpeg',
  ),
  Huissier(
    name: 'عادل لحمام',
    frenchName: 'Adil Lahmam',
    court: 'ابتدائية وزان',
    phone: '0614485646',
    email: '',
    address: 'حي الحدادين زنقة الجديدة رقم 34 مكرر وزان',
    decision: '2018/181',
    photoUrl: 'assets/images/huissiers/73.jpeg',
  ),
  Huissier(
    name: 'بشرى الفاضلي',
    frenchName: 'Bouchra Fadili',
    court: 'ابتدائية وزان',
    phone: '0652685916',
    email: 'Fadilibouchra.hj.ouazzane@gmail.com',
    address: 'إقامة نور عمارة 4 شقة 8 ليرالك أمام العمالة وزان',
    decision: '2018/323',
    photoUrl: 'assets/images/huissiers/74.jpeg',
  ),
  Huissier(
    name: 'إبراهيم جابر',
    frenchName: 'Brahim Jabar',
    court: 'ابتدائية وزان',
    phone: '0622916063',
    email: 'jabarhuissier@gmail.com',
    address: 'الشقة رقم 1 الطابق الأرضي حي الغدير تجزئة الفرح رقم 10 وزان',
    decision: '2025/583',
    photoUrl: 'assets/images/huissiers/75.jpeg',
  ),
  Huissier(
    name: 'محمد حباري',
    frenchName: 'Mohammed Habbari',
    court: 'ابتدائية وزان',
    phone: '0602525416',
    email: 'habbari.huissier@gmail.com',
    address: 'الشقة رقم 1 الطابق الأرضي حي الغدير تجزئة الفرح رقم 10 وزان',
    decision: '2025/586',
    photoUrl: 'assets/images/huissiers/76.jpeg',
  )
];
